version: '2'
services:
  php:
    container_name: php_helpee
    build: ./docker/php
    volumes:
      - ./:/var/www/helpee-sf
      - ./docker/php/conf:/usr/local/etc/php
    working_dir: /var/www/helpee-sf
    expose:
      - "5432"
      - "9000"
    ports:
      - "9000:9000"
    links:
      - elasticsearch
      - postgres
      - redis
    networks:
      - local_default
  postgres:
    build: ./docker/postgres/
    container_name: pg_helpee
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - local_default
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    hostname: redis
    volumes:
      - redis-data:/data
    networks:
      - local_default
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
    environment:
      - cluster.name=helpee_search
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    expose:
      - "9200"
    ports:
      - "9200:9200"
    networks:
      - local_default
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.8.2
    links:
      - elasticsearch
    expose:
      - "9200"
    ports:
      - "5601:5601"
    networks:
      - local_default

volumes:
  redis-data:
  pg-data:
  esdata:

networks:
  local_default:
    external: true
